### ISSUE TITLE
[bug] panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by jarrodb** [sbezverk/gobmp#221]
Saving this output here for visibility and future reference when troubleshooting:

```
E0518 21:13:59.110857       1 gobmpsrv.go:95] fail to recover BMP message Common Header with error: invalid version in common header, expected 3 found 241
panic: runtime error: makeslice: len out of range

goroutine 954 [running]:
github.com/sbezverk/gobmp/pkg/gobmpsrv.(*bmpServer).bmpWorker(0xc000024600, {0x972b30?, 0xc000012030})
        /workdir/pkg/gobmpsrv/gobmpsrv.go:99 +0x62e
created by github.com/sbezverk/gobmp/pkg/gobmpsrv.(*bmpServer).server
        /workdir/pkg/gobmpsrv/gobmpsrv.go:53 +0x16a
```

**Comment by sbezverk** [comment]
@jarrodb thank you for reporting the panic and sorry for the delay with my reply, I was off.  Is there anything specific about the environment you can add where this panic occurred? Is it easily reproducible? Processing of Common Header code has not been changed as far as I remember for ages. Curious if it is result of some new format/field recently added. Please share the vendor of BGP speaker.

**Comment by jarrodb** [comment]
Oh, I was saving it for me to remember later and troubleshoot.  The particular vendor that generated this stream was Arista.  Once I duplicate it I will submit a PR.
